### ISSUE TITLE
Wireframe and Prototypes

### ISSUE THREAD

**Issue by SaloniSS** [ReshmiCode/SummerHacks#2]
**Describe the feature**
_A clear and concise description of what the feature is._
Complete the wireframe and prototype on the [Figma Project](https://www.figma.com/file/RckvMwXVY901is1QeS9m7f/SumemrHacks?node-id=0%3A1) 

**Expected behavior**
_A clear and concise description of what you expected to happen._
The following screens are to be included:
- [x] Home screen sliders with login
- [x] Profile (with tree numbers)
- [x] Profile Settings
- [x] Log activities (with setting)
- [x] Personal Statistics
- [x] Follow users
- [x] Following
- [x] Followers
- [x] Friend Profiles
- [x] Feed
- [x] Challenges
- [x] Leaderboard

**Feature Checklist**
- [x] Documentation included
- [x] Comments included
- [x] Feature follows contributing guide
- [x] Functionality done
- [x] UI / UX done

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
_Add any other context about the problem here._

**Comment by ReshmiCode** [comment]
no u

**Comment by SaloniSS** [comment]
Added 2 more screens: friend profile and personal statistics
